
version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
